# Generated by Django 5.1.2 on 2024-11-23 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_of_users', models.IntegerField(default=1)),
                ('last_time', models.IntegerField(default=30)),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
    ]
