# Generated by Django 5.1.2 on 2024-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebWithLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='item',
            name='num_of_users',
            field=models.IntegerField(default=1),
        ),
    ]
