# Generated by Django 5.1.2 on 2024-10-31 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebWithLogin', '0002_item_last_time_item_num_of_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
