# Generated by Django 5.1.2 on 2024-11-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebWithLogin', '0003_item_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='commend',
            field=models.BooleanField(default=False),
        ),
    ]
