# Generated by Django 5.1.2 on 2024-11-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebWithLogin', '0004_item_commend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='commend',
            new_name='recommend',
        ),
    ]
