# Generated by Django 5.1.2 on 2024-11-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebWithLogin', '0005_rename_commend_item_recommend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='recommend',
            new_name='recommended',
        ),
    ]
