# Generated by Django 5.1.2 on 2024-11-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebWithLogin', '0006_rename_recommend_item_recommended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='recommended',
            new_name='recommanded',
        ),
    ]
